shadow = false
borders = "none"

[colors]
    background = "black"
    shadow     = ["#000000", "black"]
    view       = "#363636"

    primary   = ["#111111"]
    secondary = "#EEEEEE"
    tertiary  = "#444444"

    title_primary   = "#ff5555"
    title_secondary = "#ffff55"

    highlight          = "#a1a1a1"
    highlight_inactive = "#4a4a4a"