shadow = false
borders = "none"

[colors]
    background = "black"
    shadow     = ["#000000", "black"]
    view       = "#363636"

    primary   = ["#b8b8b8"]
    secondary = "#EEEEEE"
    tertiary  = "#444444"

    title_primary   = "#ffffff"
    title_secondary = "#a1a1a1"

    highlight          = "#7d7d7d"
    highlight_inactive = "#7d7d7d"